[package]
name = "superconductor"
version = "0.1.0"
authors = ["Jaden Carver <jaden.carver@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
maud = "*"
maud_macros = "*"
libc = "*"
git2 = "0.6"
serde = "0.9.8"
serde_json = "0.9.8"
serde_derive = "0.9.8"
